### PR TITLE
Add more information to session detail page

### PR DESCRIPTION
**Pull request by kerryarchibald**
For https://github.com/matrix-org/matrix-authentication-service/issues/1550

Compatibility session:
Screenshot 2023-08-31 at 17 44 01
Oauth2 session:
Screenshot 2023-08-31 at 17 30 39

- adds link from session tile title to detail page
- adds details to detail page

In next PRs:
- handling route params to redirect to detail

### CODE REVIEW

**Review by sandhose — APPROVED** [review]
Not sure about the infos that are shown here (@pmaier1 @Johennes?), but on the code side LGTM

**Comment by Johennes** [comment]
The displayed fields look like a good start to me. So given that we have only one day left before the deadline, I wouldn't block this pull request on it. If needed, we can follow up afterwards.

If the logo would be trivial to include, agree that it would be a pretty fancy addition. 🙂

**Comment by kerryarchibald** [comment]
Made a ticket for logo, will work on it after the redirect if I have time https://github.com/matrix-org/matrix-authentication-service/issues/1672

**Comment by pmaier1** [comment]
Looks good for now, thanks. Some fields are certainly a bit technical and need design review but we can do that in a later release.

**Pull request merged**
